package com.jam.train.gradbatis.mybatis.mapper;

import com.jam.train.gradbatis.mybatis.domain.SysPrvilege;

public interface SysPrvilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    int insert(SysPrvilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    int insertSelective(SysPrvilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    SysPrvilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysPrvilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_prvilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPrvilege record);
}