package com.jam.train.gradbatis.mybatis.mapper;

import com.jam.train.gradbatis.mybatis.domain.URolePermission;

public interface URolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insert(URolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(URolePermission record);
}