package com.jam.train.gradbatis.mybatis.domain;

public class SysPrvilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prvilege.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prvilege.privilege_name
     *
     * @mbg.generated
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_prvilege.privilege_url
     *
     * @mbg.generated
     */
    private String privilegeUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prvilege.id
     *
     * @return the value of sys_prvilege.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prvilege.id
     *
     * @param id the value for sys_prvilege.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prvilege.privilege_name
     *
     * @return the value of sys_prvilege.privilege_name
     *
     * @mbg.generated
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prvilege.privilege_name
     *
     * @param privilegeName the value for sys_prvilege.privilege_name
     *
     * @mbg.generated
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_prvilege.privilege_url
     *
     * @return the value of sys_prvilege.privilege_url
     *
     * @mbg.generated
     */
    public String getPrivilegeUrl() {
        return privilegeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_prvilege.privilege_url
     *
     * @param privilegeUrl the value for sys_prvilege.privilege_url
     *
     * @mbg.generated
     */
    public void setPrivilegeUrl(String privilegeUrl) {
        this.privilegeUrl = privilegeUrl;
    }
}